version: "3"
services:
  digicoapi:
    build: .
    volumes:
      - ./:/scripts:ro
      - ./data:/data:ro
      - ./log/uwsgi:/log/uwsgi
    ports:
      - 5000:5000
    environment:
      TZ: Asia/Tokyo
    restart: always
    command: >
      /bin/bash -c "
      cd /scripts &&
      uwsgi --enable-threads --ini /scripts/uwsgi.ini"
  nginxserver:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
      - ./vue:/vue:ro
    links:
      - digicoapi
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    restart: always
  htmlBuilder:
    image: node:12
    volumes:
      - ./vue:/scripts
    command: >
      /bin/bash -c "
      cd /scripts &&
      yarn install --force &&
      yarn run build"
