FROM u6kapps/open-jtalk-api

RUN cd ../ && wget "https://jaist.dl.sourceforge.net/project/mmdagent/MMDAgent_Example/MMDAgent_Example-1.8/MMDAgent_Example-1.8.zip" && unzip MMDAgent_Example-1.8.zip && cp $(find $(pwd) | grep "mei_normal") /usr/local/lib/hts_voice_nitech_jp_atr503_m001-1.05/nitech_jp_atr503_m001.htsvoice
